- name: increase max_map_count
  command: sysctl -w vm.max_map_count=262144

- name: Create Kibana configuration file
  vars:
    - elastic_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  template: 
    src: kibana.yml.j2 
    dest: /etc/custom_kibana.yml

- name: Setup docker-compose file.
  template:
    src: elastic_search.yml.j2
    dest: docker-compose.yml

- name: Start docker stack.
  command: docker-compose up -d
