---

- name: Make the DB instance active.
  hosts: localhost
  user: gce-user
  vars_files:
    - vars/db.yml
    - vars/gce.yml
    - vars/vault.yml
  roles:
    - make_instance
    
- name: Create gcs-user
  hosts: "tag_{{db_name}}"
  vars_files:
    - vars/db.yml
    - vars/vault.yml
  roles:
    - create_user
  become: root

- name: Install and run DB-server from the DB instance
  hosts: "tag_{{db_name}}"
  vars_files:
    - vars/db.yml
    - vars/vault.yml
  user: gce-user
  roles:
    - common
    - mysql


- name: Create some magento VMs based on number in magento.yml
  hosts: localhost
  vars_files:
    - vars/magento.yml
    - vars/gce.yml
    - vars/vault.yml
  roles:
    - make_instance

- name: Make those VMs active
  hosts: localhost
  vars_files:
    - vars/magento.yml
    - vars/gce.yml
    - vars/vault.yml
  roles:
    - make_instance_active


- name: Create gcs-user
  hosts: "tag_{{magento_name}}"
  vars_files:
    - vars/magento.yml
    - vars/vault.yml
  roles:
    - create_user
  become: root


- name: Install magento, MySQL client, httpd, PHP into GCE template
  hosts: "tag_{{magento_name}}"
  user: gce-user
  vars_files:
    - vars/magento.yml
    - vars/vault.yml
  roles:
    - common
    - mysql_client
    - httpd
    - php
    - magento

- name: Generate a load balancing service
  hosts: localhost
  user: gce-user
  vars:
    instance_tag: load_balance
  roles:
    - make_lb_service

- name: Deactivate template instance
  hosts: localhost
  user: gce-user
  vars_files:
    - vars/magento.yml
    - vars/vault.yml
  roles:
    - deactivate_instance