---
- name: Make the DB instance active.
  hosts: localhost
  user: gce-user
  vars:
    instance_tag: db
    vm_metadata: '{"db":"mysql", "group":"db"}'
    size_disk: 30
    type_machine: g1-small
  roles:
    - make_instance
    

- name: Install and run DB-server from the DB instance
  hosts: tag_db
  user: gce-user
  roles:
    - common
    - mysql


- name: Make a Standard VM active for templating
  hosts: localhost
  vars:
    instance_tag: magento_template
    vm_metadata: '{"db":"mysql", "group":"magento"}'
    size_disk: 15
    type_machine: n1-standard-1
  roles:
    - make_instance


- name: Install magento, MySQL client, httpd, PHP into GCE template
  hosts: tag_magento_template
  user: gce-user
  roles:
    - common
    - mysql_client
    - httpd
    - php
    - magento


- name: Deactivate template instance
  hosts: localhost
  user: gce-user
  vars:
    instance_tag: magento_template
    type_machine: n1-standard-1
  roles:
    - deactivate_instance


- name: Create image from template VM boot disk
  hosts: localhost
  user: gce-user
  roles:
    - make_image


- name: Make an instance template from the magento VM
  hosts: localhost
  user: gce-user
  roles:
    - make_template


- name: Generate a GCE managed instance group from template
  hosts: localhost
  user: gce-user
  vars:
    instance_tag: magento_instance_group
    vm_metadata: '{"db":"mysql", "group":"magento_mig"}'
    type_machine: n1-standard-1
  roles:
    - make_instance_group



- name: Generate a load balancing service
  hosts: localhost
  user: gce-user
  vars:
    instance_tag: load_balance
  roles:
    - make_lb_service


- name: Install and run apache JMeter into a separate GCE instance.
  hosts: tag_jmeter
  user: gce-user
  roles:
    - common
    - apachejmeter