- name: Install and run DB-server from a GCE instance
  hosts: tag_db
  user: gce-user
  roles:
    - common
    - mysql


- name: Install and generate a magento, MySQL client, httpd, PHP GCE template
  hosts: tag_magento_template
  user: gce-user
  roles:
    - common
    - mysql_client
    - httpd
    - php
    - magento
    - make_template


- name: Generate a GCE managed instance group from template
  hosts: tag_magento
  user: gce-user
  roles:
    - common
    - make_instance_group


  roles:
    - common
    - apachejmeter