- name: Deactivate elastic instance
  hosts: localhost
  var_files:
    - vars/elastic_search.yml
    - vars/vault.yml
    - vars/gce.yml
  roles:
    - deactivate_instance

- name: Deactivate all Magento instances + load balancing
  hosts: localhost
  vars_files:
    - vars/magento.yml
    - vars/vault.yml
    - vars/gce.yml
    - vars/lb_hc.yml
  roles:
    - deactivate_instance
    - deactivate_lb_service

- name: Deactivate the DB instance
  hosts: localhost
  vars_files:
    - vars/vault.yml
    - vars/gce.yml
    - vars/db.yml
  roles:
    - deactivate_instance
