- name: Deactivate elastic instance
  hosts: localhost
  vars_files:
    - vars/gce.yml
    - vars/config.yml
    - vars/elastic_search.yml
    - vars/vault.yml
  roles:
    - deactivate_instance


- name: Deactivate the DB instance
  hosts: localhost
  vars_files:
    - vars/config.yml
    - vars/gce.yml
    - vars/db.yml
    - vars/vault.yml
  roles:
    - deactivate_instance

- name: Deactivate all Magento instances
  hosts: localhost
  vars_files:
    - vars/config.yml
    - vars/magento.yml
    - vars/gce.yml
    - vars/vault.yml
  vars:
    - instance_name: "{{magento_name}}"
  roles:
    - deactivate_instance

#- name: Deactivate load balancer
#  hosts: localhost
#  vars_files:
#    - vars/config.yml
#    - vars/magento_manager.yml
#    - vars/gce.yml
#    - vars/vault.yml
#  roles:
#    - deactivate_lb_service

