
- name: Make the DB instance active.
  hosts: localhost
  user: gce-user
  vars_files:
    - vars/db.yml
    - vars/gce.yml
    - vars/vault.yml
  roles:
    - make_instance
    - make_instance_active
    
- name: Create gcs-user
  hosts: "tag_{{db_name}}"
  vars_files:
    - vars/db.yml
    - vars/vault.yml
  roles:
    - create_user
  become: root

- name: Install and run DB-server from the DB instance
  hosts: "tag_{{db_name}}"
  vars_files:
    - vars/db.yml
    - vars/vault.yml
  user: gce-user
  roles:
    - common
    - mysql


- name: Create and activate some magento VMs based on number in magento.yml
  hosts: localhost
  vars_files:
    - vars/magento.yml
    - vars/gce.yml
    - vars/vault.yml
  roles:
    - make_instance
    - make_instance_active


- name: Create gcs-user
  hosts: "tag_{{magento_name}}"
  vars_files:
    - vars/magento.yml
    - vars/vault.yml
  roles:
    - create_user
  become: root


- name: Install magento, MySQL client, httpd, PHP into GCE template
  hosts: "tag_{{magento_name}}"
  connection: ssh
  user: gce-user
  vars_files:
    - vars/magento.yml
    - vars/vault.yml
  roles:
    - common
    - mysql_client
    - httpd
    - php
    - magento

- name: Generate and activate a load balancing service
  hosts: localhost
  user: gce-user
  vars_files:
    - vars/magento.yml
    - vars/vault.yml
    - vars/gce.yml
    - vars/lb_hc.yml
  roles:
    - make_lb_service
    - make_lb_service_active
