---
- name: Generate and activate a load balancing service
  hosts: localhost
  vars_files:
    - vars/config.yml
    - vars/magento.yml
    - vars/vault.yml
    - vars/gce.yml
    - vars/lb_hc.yml
  roles:
    - make_lb_service
    - make_lb_service_active

