---
- name: Deactivate an instance.  
  gce:
    instance_names: "{{ item }}"
    zone: europe-west1-c
    machine_type: "{{type_machine}}"
    image_family: "{{instance_image_family}}"
    state: stopped
    disk_auto_delete: true
    service_account_email: "{{service_account_email}}"
    credentials_file: "{{credentials_file}}"
    project_id: "{{project_id}}"
  with_inventory_hostnames:
    - tag_{{instance_name}}
