- name: Activate the Load-balancer if down.
  gce_lb:
    name: "{{instance_tag}}"
    region: europe-west1
    members: "{{item}}"
    httphealthcheck_name: "{{ http_healthcheck}}"
    httphealthcheck_port: 80
    httphealthcheck_path: "{{httphealthcheck_path}}"
    state: active
    with_inventory_hostnames:  
      - "tag_{{magento_name}}"
    