version: "3"
services:
  magento:
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
    labels:
      magento.container: "Magento"
    image: magento:latest
    ports:
      - "9000:9000"
      - "3306:3306"
    networks:
      - webnet
    volumes:
      - "php:/var/www/magento2"
  web:
    # replace username/repo:tag with your name and image details
    image: andrediogo92/nginx-mage:latest
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
    labels:
      web.container: "Nginx"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    volumes:
      - "php:/var/www/html/magento2"
      - "./vhosts.conf:/etc/nginx/conf.d/default.conf"
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.1.2
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
    labels:
      metricbeat.container: "Metricbeat"
    networks:
      - webnet
    volumes:
      - "/etc/metricbeatscfg/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml"
      - "/etc/metricbeatscfg/modules.d/:/usr/share/metricbeat/modules.d/"
networks:
  webnet:
volumes:
  php:
