---
- name: Ensure /var/www/html/ exists
  command: mkdir /var/www/html/magento
  become: root

- name: Copy Magento to VM
  copy:
    src: Magento-CE-2.2.2.tar
    dest: /var/www/html/magento/Magento-CE-2.2.2.tar

- name: Extract Magento
  command: chdir=/var/www/html/magento /bin/tar xvf Magento-CE-2.2.2.tar

- name: Permissions
  command: chdir=/var/www/html/magento find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \;

- name: Permissions
  command: chdir=/var/www/html/magento find var vendor pub/static pub/media app/etc -type d -exec chmod u+w {} \;

- name: Permissions
  command: chdir=/var/www/html/magento chmod u+x bin/magento

- name: Create magento database
  mysql_db: name={{ magento_db_name }} state=present

- name: Create magento database user
  mysql_user: name={{ magento_db_user }} password={{ magento_db_password }} priv={{ magento_db_name }}.*:ALL host={{ hostvars['db']['ansible_default_ipv4']['address'] }} state=present

- name: Install Magento
  command: chdir=/var/www/html/magento/bin magento setup:install

- name: restart iptables
  service: name=iptables state=restarted

- name: restart httpd
  service: name=httpd state=restarted