---
- name: Install Mysql package
  apt: 
    name: "{{ item }}" 
    state: present
    with_items:
      - mysql-server-5.7
      - libselinux1
      - libsemanage1

- name: Create Mysql configuration file
  template: 
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify:
    - restart mysql

- name: Start Mysql Service
  service: 
    name: mysqld 
    state: started 
    enabled: true
