---
- name: Install php repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
    update_cache: yes

- name: Install Mysql package
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
    - mysql-server
    - python-mysqldb
    - php7.1-mysql 
    - libselinux1
    - libsemanage1


- name: Create Mysql configuration file
  template: 
    src: my.conf.j2 
    dest: /etc/my.cnf
  notify:
    - restart mysql

- name: Start Mysql Service
  service: 
    name: mysql
    state: started 
    enabled: true


