# Create number_VMs Ubuntu 17_10 instances in the europe-west1-c Zone.
# Add tags and metadata.
- name: "Create {{number_VMs}} instances."  
  gce:
    name: "{{instance_tag}}"
    zone: europe-west1-c
    machine_type: "{{type_machine}}"
    image_family: ubuntu-1710
    state: present
    num_instances: "{{number_VMs}}"
    metadata: "{{vm_metadata}}"
    tags:
      - "{{instance_tag}}"
    disk_size: "{{size_disk}}"
    disk_auto_delete: true
    ip_forward: true
    service_account_email: "{{service_account_email}}"
    credentials_file: "{{credentials_file}}"
    project_id: "{{project_id}}"
  register: gce

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
  with_items: "{{ gce.instance_data }}"