# Activate number_VMs Ubuntu 17_10 instances in the europe-west1-c Zone.
# Add tags and metadata.
- name: "Activate {{number_VMs}} of instances."  
  gce:
    name: "{{instance_name}}"
    zone: europe-west1-c
    machine_type: "{{type_machine}}"
    image_family: "{{instance_image_family}}"
    state: started
    num_instances: "{{number_VMs}}"
    metadata: "{{vm_metadata}}"
    tags:
      - "{{instance_tag}}"
    disk_size: "{{size_disk}}"
    disk_auto_delete: true
    ip_forward: true
    service_account_email: "{{service_account_email}}"
    credentials_file: "{{credentials_file}}"
    project_id: "{{project_id}}"
