---
- name: Copy magento install template with known db host.
  vars:
    - db_host: "{{hostvars[groups['tag_' + db_name][0]]['ansible_default_ipv4']['address']}}"
  template:
    src: Dockerfile.j2
    dest: ./Dockerfile

- name: Copy Nginx vhosts.conf.
  copy:
    src: vhosts.conf
    dest: ./vhosts.conf

- name: Pull docker image to cache ASAP.
  command: docker pull andrediogo92/magento-php:latest
