- name: Open port 80
  shell: iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT

- name: Save Iptables
  shell: /etc/init.d/iptables save

- name: Install apache
  apt: 
    name: "{{item}}" 
    state: present
    with_items:
      - apache2

- name: Install apache modules
  apache2_module:
    name: "{{item}}"
    state: present
    with_tiems:
      - rewrite

- name: httpd Start initial
  service: 
    name: httpd 
    state: started 
    enabled: yes

- name: Create Folder
  command: mkdir -p /etc/httpd/vhost.d/

- name: Copy httpd configuration for httpd
  template: 
    src: httpd.conf 
    dest: /etc/httpd/conf/httpd.conf

- name: Copy httpd configuration for domain whithout varnish
  template: 
    src: vhost.conf 
    dest: /etc/httpd/vhost.d/{{ server_hostname }}.conf

- name: Copy httpd configuration for ports without varnish
  template: 
    src: ports.conf 
    dest: /etc/httpd/ports.conf
  notify: restart httpd
