- name: Install apache
  apt: 
    name: "{{item}}" 
    state: present
    with_items:
      - apache2

- name: Install apache modules
  apache2_module:
    name: "{{item}}"
    state: present
    with_tiems:
      - rewrite