- name: Open port 80
  shell: iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT

- name: Save Iptables
  shell: /sbin/iptables-save

- name: Install apache
  apt: 
    name: "{{item}}" 
    state: present
  with_items:
    - apache2

- name: Install apache modules
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - rewrite

- name: httpd Start initial
  service: 
    name: apache2
    state: started 
    enabled: yes

- name: Create Folder
  command: mkdir -p /etc/httpd/vhost.d/

- name: Copy httpd configuration for httpd
  template: 
    src: httpd.conf 
    dest: /etc/httpd/conf/httpd.conf

- name: Copy httpd configuration for domain whithout varnish
  template: 
    src: vhost.conf 
    dest: /etc/httpd/vhost.d/vhost.conf

- name: Copy httpd configuration for ports without varnish
  template: 
    src: ports.conf 
    dest: /etc/httpd/ports.conf
  notify: restart httpd

- name: restart iptables
  service: name=iptables state=restarted
  when: magento_install != 'install'

- name: restart httpd
  service: name=httpd state=restarted
  when: magento_install != 'install'