- name: Update apt-cache
  apt:
    update-cache: yes
    upgrade: full

- name: Install common needed stuff
  apt: 
    name: "{{item}}" 
    state: present
  with_items:
    - software-properties-common
    - wget
    - vim
    - nano