---
- name: Install php repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
    update_cache: yes

- name: Install php and deps
  apt: 
    name: "{{ item }}" 
    state: present
    with_items:
      - wget
      - php7.1 
      - libapache2-mod-php7.1 
      - php7.1-common 
      - php7.1-gd 
      - php7.1-mysql 
      - php7.1-mcrypt 
      - php7.1-curl 
      - php7.1-intl 
      - php7.1-xsl 
      - php7.1-mbstring 
      - php7.1-zip 
      - php7.1-bcmath 
      - php7.1-iconv 
      - php7.1-soap

- name: Install composer will only run when log.txt doesn't exist.
  shell: composer.sh
  args:
    creates: log.txt
  register: result

- name: Restart apache on installation success
  notify: restart httpd
  when: result|succeeded